services:
  - type: web
    name: class-management-system
    env: static
    buildCommand: npm ci && PUBLIC_URL=. npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
